2023-12-30 04:24:20,846 - ERROR - Exception on /search [GET]
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\DELL\OneDrive\Desktop\FURTHER UPGRADE\cs50_final_project\app\routes.py", line 376, in search
    return render_template('search.html')
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\DELL\OneDrive\Desktop\FURTHER UPGRADE\cs50_final_project\app\templates\search.html", line 3, in top-level template code
    {% extends "layout.html" %}
  File "C:\Users\DELL\OneDrive\Desktop\FURTHER UPGRADE\cs50_final_project\app\templates\layout.html", line 93, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\DELL\OneDrive\Desktop\FURTHER UPGRADE\cs50_final_project\app\templates\search.html", line 7, in block 'content'
    {{ form.csrf_token }}
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2023-12-30 04:25:43,187 - ERROR - Exception on /search [GET]
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\DELL\OneDrive\Desktop\FURTHER UPGRADE\cs50_final_project\app\routes.py", line 376, in search
    return render_template('search.html')
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\DELL\OneDrive\Desktop\FURTHER UPGRADE\cs50_final_project\app\templates\search.html", line 3, in top-level template code
    {% extends "layout.html" %}
  File "C:\Users\DELL\OneDrive\Desktop\FURTHER UPGRADE\cs50_final_project\app\templates\layout.html", line 93, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\DELL\OneDrive\Desktop\FURTHER UPGRADE\cs50_final_project\app\templates\search.html", line 7, in block 'content'
    {{ form.csrf_token }}
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2023-12-30 05:00:11,095 - ERROR - Exception on /search [POST]
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\DELL\OneDrive\Desktop\FURTHER UPGRADE\cs50_final_project\app\routes.py", line 382, in search
    return render_template('search.html', title='Search Results', form=form, search_results=search_results)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\DELL\OneDrive\Desktop\FURTHER UPGRADE\cs50_final_project\app\templates\search.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "C:\Users\DELL\OneDrive\Desktop\FURTHER UPGRADE\cs50_final_project\app\templates\layout.html", line 93, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\DELL\OneDrive\Desktop\FURTHER UPGRADE\cs50_final_project\app\templates\search.html", line 27, in block 'content'
    <td><a  href="/user/{{ post.author.username }}">{{ result['post_title'] }}</a></td>
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'post' is undefined
2025-01-01 18:48:56,606 - ERROR - An error occurred in admin_users route: 'flask_login.mixins.AnonymousUserMixin object' has no attribute 'has_admin_privileges'
Traceback (most recent call last):
  File "d:\old laptop\2024\FURTHER UPGRADE\cs50_final_project\app\routes.py", line 299, in post
    return render_template('post.html', title = post.title, post = post,image = image_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\noors\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\noors\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\noors\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\noors\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "d:\old laptop\2024\FURTHER UPGRADE\cs50_final_project\app\templates\post.html", line 1, in top-level template code
    {%extends "layout.html"%}
  File "d:\old laptop\2024\FURTHER UPGRADE\cs50_final_project\app\templates\layout.html", line 103, in top-level template code
    {% block content %}
  File "d:\old laptop\2024\FURTHER UPGRADE\cs50_final_project\app\templates\post.html", line 10, in block 'content'
    {%if post.author == current_user or current_user.has_admin_privileges() %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\noors\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\jinja2\utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'flask_login.mixins.AnonymousUserMixin object' has no attribute 'has_admin_privileges'
